version: 2
enable-beta-ecosystems: true

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "pip"
      directory: "/test"
      schedule:
          interval: "daily"
      versioning-strategy: increase
